# similar to dictionary but immutable (create copy each changes)
empty = ()
print(empty)
numbers = (1, 2, 3, 4, 5)
numbers2 = (3, 4)
print(numbers[0] + numbers[2])
print(len(numbers))
print(numbers[0:2])
print(numbers + numbers2)
sentence = ('now', 'is', 'the', 'time')
print(sentence)
print(sentence * 3)
